### ISSUE TITLE
Storing approved dependencies

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu/DependencyReviewer#1]
For the moment, I just put example approved dependencies here: https://github.com/darwin-eu/DependencyReviewer/blob/main/R/getDefaultPermittedPackages.R

Would be better to save a csv with these (along with a description) which can be used in the package and added to the readme.

**Comment by mvankessel-EMC** [comment]
Dependencies are now in a [separate repository](https://github.com/mvankessel-EMC/DependencyReviewerWhitelists/), like Deck/DeckR.
