### ISSUE TITLE
Request dependencies

### ISSUE THREAD

**Issue by mvankessel-EMC** [darwin-eu/DependencyReviewer#6]
This issue has been deprecated. Submit your requests [here](https://github.com/mvankessel-EMC/DependencyReviewerWhitelists/issues).

**Comment by ablack3** [comment]
|package |version |date                | downloads_last_month|license                 |url                                                                |
|:-------|:-------|:-------------------|--------------------:|:-----------------------|:------------------------------------------------------------------|
|arrow   |10.0.0  |2022-10-26 12:25:07 |                72782|Apache License (>= 2.0) |https://github.com/apache/arrow/, https://arrow.apache.org/docs/r/ |
|waldo   |0.4.0   |2022-03-16 21:20:04 |               495045|MIT + file LICENSE      |https://waldo.r-lib.org, https://github.com/r-lib/waldo

**Comment by ablack3** [comment]
|package      |version |date                | downloads_last_month|license               |url |
|:------------|:-------|:-------------------|--------------------:|:---------------------|:---|
|CDMConnector |0.1.0   |2022-09-29 15:50:02 |                  274|Apache License (>= 2) |NA  |
